name: Deploy Zendesk App to SB1 when code is pushed to uat branch

on:
  push:   
    branches: 
      - uat-**

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:     
      - uses: zendesk/checkout@v2
      
      - name: Add ZAT Config
        env:
          ZAT_SB1: ${{ secrets.ZAT_SB1 }}
        run: |
          echo $ZAT_SB1 >> .zat
      
      - name: ZAT Deploy
        uses: zendesk/zat-deploy@master
